platform :ios, '10.0'

target 'SketchCollage' do
  use_frameworks!


pod 'PromiseKit', '~> 6.5.2'
pod 'SnapKit', '~> 4.2.0'
pod 'SKPhotoBrowser', '~> 6.0.0'
pod 'Alamofire', '~> 4.7.3'
pod 'SwiftyJSON', '~> 4.2.0'
pod 'PKHUD', '~> 5.2.0'
pod 'Kingfisher', '~> 4.10.0'
pod 'MJRefresh', '~> 3.1.15.7'

#pod 'RxSwift', '~> 4.0'
#pod 'RxCocoa', '~> 4.0'
#pod 'JTAppleCalendar', '~> 7.0'


#This is Third Lib

pod 'mob_smssdk', '~> 3.2.3'



end





